### ISSUE TITLE
خطای اجرای برنامه

### ISSUE THREAD

**Issue by mhabibi** [MasoodKamali/Testprj#1]
بعد از نصب دیتابیس در صفحه index.php‌خطای 500 server error‌دریافت می شود.
سرور وب: nginx

**Comment by MasoodKamali** [comment]
با سلام
چون موتور اصلی سایت تنظیمات خاص htaccess را دارد
بباید از wampserver2.2 استفاده کنی که موتور 
appache 2.2.21 را بالا بیارد 
از nginx استفاده کنی باید تننظیمات htaccess تغییر بدی که زمان بر هست
با تشکر

---

Hi
If you use nginx server must htaccess file to change . Because it is so time consuming to install wampserver2.2 and use of motor appache 2.2.21 .

**Comment by mhabibi** [comment]
چرا اکه تنظیمات خاص اچ تی اکسس داره، فایل اچ تی اکسس داخل پروژه نیست؟

**Comment by MasoodKamali** [comment]
به خاطر امنیت سایت تغییرات را در موتور خود سایت در اسمارتی ها انجام می دم

**Comment by mhabibi** [comment]
حالا نهایتا چطوری میشه این پروژه رو اجرا کرد؟ راه حلش چیه؟

**Comment by MasoodKamali** [comment]
رفیق  wampserver2.2 را نصب کن
با wamp کار کردی؟

**Comment by MasoodKamali** [comment]
ومپ نرم افزاری که سه موتور پی اچ پی و اپاچی و مای اس کیول را با هم داره
مجانی هم هست
کار باهاش ساده است

**Comment by mhabibi** [comment]
نه، من لینوکس استفاده میکنم، وب سرور هم انجین ایکس.

**Comment by MasoodKamali** [comment]
پس باید من موتور سایت را برا اساس انجین ایکس تغییر بدم بعد فایل ها را بروز کنم

**Comment by MasoodKamali** [comment]
من پروژه را با اینجین ایکس 1.6  و با پی اچ پی 5.3.8  چک کردم مشکلی نبود
شما چه ورژن انجین ایکس و پی اچ پی را استفاده می کنی؟
